### ISSUE TITLE
HAVING function not mentioned in lessons but needed to complete lab

### ISSUE THREAD

**Issue by mirc89** [learn-co-curriculum/sql-crowdfunding-lab#14]
According to W3School "The HAVING clause was added to SQL because the WHERE keyword could not be used with aggregate functions."

sql-crowdfunding lab has us 'selects_the_titles_of_all_projects_that_have_met_their_funding_goal' which requires a function and a clause to return only the projects that have a pledging amount the same of more than it's goal. It would be great to mention in "Grouping And Sorting Data" when to use where / having.

**Comment by MsUzoAgu** [comment]
@mirc89: Thanks for pointing out the discrepancy. It's been fixed now. 

cc @AnnJohn
