### ISSUE TITLE
Possible spec error

### ISSUE THREAD

**Issue by jsgoldb** [learn-co-curriculum/sql-crowdfunding-lab#16]
I believe for the spec:
```ruby
it '#selects_the_titles_of_all_projects_that_have_met_their_funding_goal' do
      expect(@db.execute(selects_the_titles_of_all_projects_that_have_met_their_funding_goal)).to eq([["My book on SQL", 0], ["The next Inna-Gadda-Davida", -142]])
    end
```
the -142 should be 142. I had everything correct except I was returning 142 and not -142, including the other example. 142 also makes more sense given what the query is trying to accomplish.

**Comment by AnnJohn** [comment]
thanks @jsgoldb for raising this. We'll look into it and update.
