### ISSUE TITLE
Rspec typo: "user" for "users"

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/sql-crowdfunding-lab#17]
In the Rspec, lines 38-48, it refers to a "user" table, but tests a "users" table, raising "no such table."

` it "creates a user table with an id as a primary key" do
      expect(@db.execute("PRAGMA table_info(users);").detect { |arr| arr[-1] == 1 && arr[2] == "INTEGER" }.length).to eq(6)
    end

    it "creates a user table with a name field" do
      expect{@db.execute("SELECT name FROM users;")}.to_not raise_exception
    end

    it "creates a user table with an age field" do
      expect{@db.execute("SELECT age FROM users;")}.to_not raise_exception
    end`

**Comment by AnnJohn** [comment]
thanks, we updated this
