### ISSUE TITLE
Wasn't able to run Learn

### ISSUE THREAD

**Issue by hudbuz** [learn-co-curriculum/sql-crowdfunding-lab#23]
Not sure if this was intentional or not, but I received this error when trying to run learn:
/Users/hudsonbuzby/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2162:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ffa81881010 learn-co-3.2.20> (NoMethodError)
	from /Users/hudsonbuzby/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/hudsonbuzby/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/hudsonbuzby/.rvm/gems/ruby-2.2.3/gems/learn-co-3.2.20/bin/learn:3:in `<top (required)>'
	from /Users/hudsonbuzby/.rvm/gems/ruby-2.2.3/bin/learn:23:in `load'
	from /Users/hudsonbuzby/.rvm/gems/ruby-2.2.3/bin/learn:23:in `<main>'
	from /Users/hudsonbuzby/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/hudsonbuzby/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

It worked fine once I ran rspec. I'm assuming an update to learn was made that wasn't expected?

**Comment by AnnJohn** [comment]
thanks for raising this @hudbuz. Since this looks like a technical problem, could you actually file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. Thanks!
