### ISSUE TITLE
Groceries in Crowdfunding

### ISSUE THREAD

**Issue by SuperConfuserUser** [learn-co-curriculum/sql-crowdfunding-lab#30]
A lesson about groceries is in the second half of the readme. It has nothing to do with the Crowdfunding Lab and seems like it might've been leftover from something else or wrongly copied and pasted.

**Comment by kargok** [comment]
The groceries section is still in the Crowdfunding lab

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
