### ISSUE TITLE
Submitted lab, but Submit Pull Request is still greyed out in lab

### ISSUE THREAD

**Issue by marysue** [learn-co-curriculum/sql-crowdfunding-lab#32]

**Comment by jenmyers** [comment]
Hi there,

Pull requests for completed labs should be opened on the appropriate repository in the learn-co-students organization. PRs submitted against learn-co-curriculum repositories should be reserved for proposed edits and improvements to the curriculum itself.

The Learn Help Center has an article on how to manually fork and clone a lab from the correct repository. If you require additional assistance, pop into Ask a Question (AAQ), where the Technical Coaches (on supported tracks) and fellow community members can provide additional help.

Thanks! 💙
