### ISSUE TITLE
Groceries?

### ISSUE THREAD

**Issue by PhilipSterling** [learn-co-curriculum/sql-crowdfunding-lab#33]
Why is there a grocery lesson in this lab? I am confused, it doesn't seem to have much to do with this lab.

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
